using SqlSugar;

namespace AttcMN.Data.Entities
{
    [SugarTable("storage", "Manager File")]
    public class Storage : CreateUserBaseEntity
    {
        // file_id is a GUID generated by the app – do NOT mark as identity.
        [SugarColumn(ColumnName = "file_id", IsPrimaryKey = true)]
        public Guid FileId { get; set; }

        [SugarColumn(ColumnName = "old_name", ColumnDescription = "File Old Name")]
        public string? OldName { get; set; }

        [SugarColumn(ColumnName = "file_path", ColumnDescription = "File Path")]
        public string? FilePath { get; set; }

        [SugarColumn(ColumnName = "file_size", ColumnDescription = "Lenght Of File")]
        public long FileSize { get; set; }

        [SugarColumn(ColumnName = "content_type", ColumnDescription = "Type Of File")]
        public string? ContentType { get; set; }

        [SugarColumn(ColumnName = "is_deleted")]
        public bool IsDeleted { get; set; }
    }
}
